### PR TITLE
Standardize output to JSON

### LINKED ISSUE #39: Standardized output (JSON or similar)
It may be a good idea to write quantities of interest to some sort of standardized format, to avoid users having to write parsers for output files.

If our quantities are small, we can use a lightweight, simple format like JSON.

If we need to output bigger quantities, we can use a binary format like HDF5. [This library](https://github.com/BlueBrain/HighFive) looks nice.

### PR DESCRIPTION
**Pull request by jcoulter12**
## Summary:
Output in phoebe now formats to JSON via the nlohmann/json library. Corresponding plot scripts to read in this format have been added under scripts/. This resolves #39.

#### CMakeLists
* nlohmann/json is now incorporated into the CMakeFile. It does not require any additional dependences, and I'm pulling from a repo which tracks the original repo, but keeps the files required to a minimum.
#### bandsApp + dosApp
* Used a helper function "outputToJSON" to reduce code reuse in bands_app and dos_app. In dos_app, code reuse was reduced further by adding a helper calcDoS function. 
* Both apps now output to JSON.
* If a fermiLevel is supplied in the input file, these apps will also output that information, along with information about the input band app and high symmetry points, to be used for plotting easily.
#### scattering.cpp
* The scattering matrix now has a function called outputToJSON which outputs lifetimes, group velocities, and the corresponding wavevectors.
#### onsager.cpp
* The Onsager coefficients can now be output via outputToJSON. We don't yet have a test case for this in phoebe, so we'll have to check it later.
#### phonon_thermal_conductivity, viscosity, specific heat, etc
* Thermal properties now have outputToJSON functions, which simply output the quantity and temperature. The function is called for different solvers in phononTransportApp.

### Plot Scripts
* I now have plot scripts for bands.py, dos.py, tau.py, and conductivity.py, which should be able to generically plot basically any JSON output, regardless of which solver was used to get the quantity, or if it's from phonons or electrons, etc.

## For reviewer: 
* A couple of the relaxation times coming out of phononTransport.in are null (likely the the acoustic modes at gamma). That might be an issue that could come to bite us later, so I wanted to mention it.
* @cepelotti, can you run the tau.py script + the phononTransport app to make sure the output is sensible? I think it mostly matches what other codes produce, but vs the alamode tutorial output, it looks like we're maybe an order of magnitude different? (Could this be a factor of 2pi difference?)
* I am currently dumping tau when the rta or relaxons solver is run. Is there another part of phononTransportApp I should dump from?
 * Is the expected scientific notation value for velocities m/s if I'm using the conversion from constants.h, velocityRyToSi?

### CODE REVIEW

**Comment by cepellotti** [comment]
Hi Jenny, the script for the thermal conductivity wasn't working for me out of the box. I modified it a bit. Can you check that it works also on your mac?

**Comment by jcoulter12** [comment]
Just tested the modified copy, works for me.

**Review by cepellotti — APPROVED** [review]
* yes, there are three null relaxation times corresponding to the acoustic modes at gamma. Yes, it may come to bite us, but in the phonon observables, we skip the acoustic modes from integration. Physically, the lifetimes of these three modes = infinity. So, even for physics these modes are a corner case. @Jenny: Do you have an idea in mind to deal with them?

* about the order of magnitude / factor of 2Pi, we have to converge the k/q points before commenting on this. If there really will be a factor 2Pi missing, we will need to debug. (could simply be a conversion factor missing) But I don't think this should block this pull request

* No other places yet, currently we compute tau only in the phononTransportApp.

* Yes, velocity is converted from atomic units to m/s using *velocityRyToSi. If the aforementioned factor of twoPi is also missing from here, it might be a problem of the conversion of time from seconds to atomic units.

**Comment by jcoulter12** [comment]
@cepellotti this all sounds good, thanks for reviewing!

* On the null relaxation times, I didn't necessarily have any fix in mind -- just wanted to make sure you were aware that was happening once I noticed them. 
* Indeed, I considered the factor of 2pi just because in the past, I've missed this when converting phonon quantities involving frequencies as opposed to angular frequency, things like this. Agreed it's not necessary for this pull request, but was again just something I wanted to mention once I saw it, before I forgot it.

**Pull request merged**
